version: '3'

services:
  algod:
    image: "sdk-harness-algod"
    container_name: sdk-harness-algod
    build:
      context: .
      dockerfile: "./docker/algod/${TYPE:-channel}/Dockerfile"
      args:
        # This is used with TYPE="channel" to override the channel.
        CHANNEL: "${CHANNEL:-nightly}"
        
        # This is used with TYPE="source" to override the git information.
        URL: "${ALGOD_URL:-https://github.com/algorand/go-algorand}"
        BRANCH: "${ALGOD_BRANCH:-master}"
    ports:
      - 60001:60001
      - 60000:60000
    networks:
      - sdk-harness

  # develop branch dataset1
  indexer-release:
    image: "sdk-harness-indexer-release"
    container_name: sdk-harness-indexer-release
    build:
      context: .
      dockerfile: ./docker/indexer/Dockerfile
      args:
        URL: "https://github.com/algorand/indexer"
        BRANCH: "develop"
        #SHA: "d5bbaf6190d27118fd8823194b4053fb01859f13"
    ports:
      - 59999:8980
    restart: unless-stopped
    networks:
      - sdk-harness
    environment:
      DATABASE_NAME: dataset1

  # Applications Branch using dataset2
  indexer-applications:
    image: "sdk-harness-indexer-applications"
    container_name: sdk-harness-indexer-applications
    build:
      context: .
      dockerfile: ./docker/indexer/Dockerfile
      args:
        URL: "https://github.com/brianolson/indexer"
        BRANCH: "app2"
    ports:
      - 59998:8980
    restart: unless-stopped
    networks:
      - sdk-harness
    environment:
      DATABASE_NAME: dataset2

  indexer-db:
    image: "postgres"
    container_name: sdk-harness-postgres
    volumes:
      - ./docker/indexer/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    networks:
      - sdk-harness
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: harness
      POSTGRES_MULTIPLE_DATABASES: dataset1, dataset2

networks:
  sdk-harness:
